channels:
- conda-forge
dependencies:
- python=3.10.9
- pip<=23.3.1
- pip:
  - mlflow==2.12.1
  - cloudpickle==3.0.0
  - numpy==1.23.5
  - packaging==23.2
  - pandas==1.5.3
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
name: mlflow-env
